pool:
  vmImage: 'Ubuntu-20.04'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - parser/*
    - parser.yml

schedules:
- cron: "20 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

steps:

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: Install Yarn 1.22.5
  inputs:
    versionSpec: 1.22.5

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: yarn install
  inputs:
    arguments: install
    projectDirectory: parser

- bash: |
    yarn test-ci
  env:
    JEST_JUNIT_OUTPUT_DIR: '$(Common.TestResultsDirectory)'
    JEST_JUNIT_OUTPUT_NAME: unit.xml
  workingDirectory: parser
  displayName: yarn test

- bash: |
    sudo apt-get update
    sudo apt-get install -y libgbm1
  displayName: Install libgbm1 (required by Puppeteer 3)

- bash: |
    yarn e2e-ci
  env:
    JEST_JUNIT_OUTPUT_DIR: '$(Common.TestResultsDirectory)'
    JEST_JUNIT_OUTPUT_NAME: e2e.xml
  workingDirectory: parser
  displayName: yarn e2e

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.xml'
    testResultsFormat: 'JUnit'
    searchFolder: $(Common.TestResultsDirectory)
  condition: succeededOrFailed()
  displayName: Publish tests results
